/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'richoti' at '5/9/18 9:27 AM' with Gradle 3.2.1
 *
 * @author richoti, @date 5/9/18 9:27 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
