import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'richoti' at '5/9/18 9:27 AM' with Gradle 3.2.1
 *
//  * @author richoti, @date 5/9/18 9:27 AM
//  */
// public class HangmanTest {
//     @Test public void testSomeLibraryMethod() {
//         Hangman classUnderTest = new Hangman();
//         assertTrue("someLibraryMethod should return 'true'", classUnderTest.randomWord());
//     }
// // 
